name: emby_viwer
description: "A cross-platform Emby media client built with Flutter. Supports iOS, Android."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # i18n
    sdk: flutter
  intl: ^0.20.2
  flutter_svg: ^2.2.3 # SVG Renderer
  cupertino_icons: ^1.0.8
  go_router: ^17.1.0 # Router
  dio: ^5.9.1 # HTTP Request
  url_launcher: ^6.3.2 # URL Launch
  fluttertoast: ^9.0.0 # Toast
  # Dto
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # Storage
  flutter_secure_storage: ^10.0.0
  # Uuid
  uuid: ^4.4.2
  # Device Info
  device_info_plus: ^12.3.0
  # Carousel Component
  carousel_slider: ^5.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  flutter_gen_runner:
  # Dto
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/
  line_length: 80
